# Generated by Django 4.1.2 on 2024-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ad", models.CharField(max_length=30)),
                ("soyad", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("sifre", models.CharField(max_length=30)),
                ("sifretekrari", models.CharField(max_length=30)),
                ("ilgi_alanlari", models.CharField(max_length=30)),
            ],
        ),
    ]
